import { commonStyles } from './common';

export const trainingGuideStyles = {
  container: commonStyles.containerWithPadding,
  title: commonStyles.heading1,
  subtitle: 'text-xl text-gray-600 mb-8',
  formContainer: 'max-w-2xl mx-auto bg-white rounded-lg shadow-lg p-8 mb-8',
  formTitle: 'text-2xl font-bold mb-6',
  formGrid: 'grid grid-cols-1 md:grid-cols-2 gap-6',
  formField: 'space-y-4',
  fullWidth: 'md:col-span-2',
  label: 'block text-sm font-medium mb-1',
  input: commonStyles.inputFocus,
  textarea: 'w-full px-4 py-2 border rounded focus:outline-none focus:ring-2 focus:ring-primary-500',
  select: commonStyles.inputFocus,
  checkboxGroup: 'space-y-2',
  checkboxItem: 'flex items-center space-x-2',
  checkbox: 'w-4 h-4 text-primary-600 focus:ring-primary-500',
  checkboxLabel: 'text-sm',
  goalsInput: 'w-full px-4 py-2 border rounded focus:outline-none focus:ring-2 focus:ring-primary-500',
  addGoalButton: 'mt-2 px-4 py-2 bg-gray-200 text-gray-700 rounded hover:bg-gray-300 text-sm',
  goalsList: 'mt-2 space-y-2',
  goalTag: 'inline-flex items-center px-3 py-1 bg-primary-100 text-primary-800 rounded-full text-sm',
  removeGoalButton: 'ml-2 text-red-600 hover:text-red-800',
  submitButton: 'w-full bg-primary-600 text-white py-3 rounded-lg font-semibold hover:bg-primary-700 disabled:bg-gray-400 transition-colors',
  guideContainer: 'max-w-4xl mx-auto bg-white rounded-lg shadow-lg p-8',
  guideContent: 'prose prose-lg max-w-none',
  disclaimer: 'bg-yellow-50 border-l-4 border-yellow-400 p-4 mb-6',
  disclaimerTitle: 'font-bold text-yellow-800 mb-2',
  disclaimerText: 'text-yellow-700 text-sm',
  loading: 'text-center py-8',
  error: 'bg-red-50 border-l-4 border-red-400 p-4 mb-6',
  errorText: 'text-red-700',
};
